### ISSUE TITLE
Account creation results in InvalidSignature error (and other output)

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-cli#105]
**Detailed Description**
Creating an account on the testnet seemingly returns valid mnemonics but returns an invalid signature error (Null Pointer Exception), leaving me unsure what went wrong.

I'm not 100% certain why this is occurring, but this could likely be due to choosing the incorrect import format, e.g., `bip39` instead of the original `hgc` during setup. However, I'd expect it not to print any results if the transaction was not successful.

I'd request that we 1) clean up error handling, only printing results if successful, and 2) prompting users to reimport their keys or otherwise if not successful.

![image](https://user-images.githubusercontent.com/11776938/68246158-1cea3380-ffcd-11e9-86e6-c53f4d44fb34.png)

**Actual Behavior**

1. `setup` a new account
2. choose `bip39` or `hgc` (the opposite of your key format)
3. attempt to create an account
4. 😢 about the invalid signature error

**Expected Behavior**

1. `setup` a new account
2. choose `bip39` or `hgc`
3. attempt to create an account
4. if 3 fails due to incorrect key format, don't print out anything aside from an error message, and prompt user to reimport with the alternative option from 2
5. make new accounts successfully with this excellent CLI tool!! 🎊 

**Environment:**
- Java: Java(TM) SE Runtime Environment (build 12.0.2+10)
- Node: v10.16.3
- OS: Mac OS, Mohave
- Version:  10.14.1

**Comment by calvinchengx** [comment]
@Cooper-Kunz 

Is this `master` branch (via git clone) or `0.0.4` installed via the brew command?

**Comment by Cooper-Kunz** [comment]
Installed with `brew`, per the readme @calvinchengx

**Comment by calvinchengx** [comment]
Fixed via 498d068

**Comment by calvinchengx** [comment]
`brew upgrade hedera-cli` should bring you up to `v0.0.5`

**Comment by calvinchengx** [comment]
Clarifications:-

for 

> I'd request that we 1) clean up error handling, only printing results if successful, and 2) prompting users to reimport their keys or otherwise if not successful.

and

> 3 fails due to incorrect key format, don't print out anything aside from an error message, and prompt user to reimport with the alternative option from 2

they have already been implemented in the latest version in `master branch` or are currently being refined in the targeted `v0.1.0` release.

498d068 fixes specifically the Null Pointer Exception big as a v0.0.5 release and nothing else.

Thanks for catching it and for your awesome feedback.

**Comment by Cooper-Kunz** [comment]
Hey @calvinchengx - I've upgraded to the newest version with `brew upgrade hedera-cli`, which seems like it attempted to get me to `v0.1.1` - rather than how I see you said `v0.5.0` and `v0.1.0`. 

However, after that upgrade, I'm still receiving the invalid signature error, however (and new output)

**Upgrading to recent version**
![image](https://user-images.githubusercontent.com/11776938/68329657-8f6b1a00-0086-11ea-9e1c-757e206ffeb6.png)

**Attempting to create an account, with the same config as above**
![image](https://user-images.githubusercontent.com/11776938/68329658-91cd7400-0086-11ea-80d4-511007cd8491.png)

Separately, it'd be great to add a `version` command, so I know which is running. I'll file a separate issue for this. 😄

**Comment by calvinchengx** [comment]
Hello, sorry if I wasn't being clear, some of the issues (user messaging and stacktrace) are being dealt with in the 0.1.X series.

There are a large number of different user messages to show user the correct feedback and each set of messages are for different functions.

So each of those need refinement and I will be assembling a checklist to review each one.

And yes, a version command is one of that.  For the repeated NPE you see in 0.1.1, this is because I forgot to cherry-pick the fix in 0.0.5 for it. Will cherrypick again and release the next patch.

For other user message features, it will have to be dealt with via a checklist approach as separate issue(s).

**Comment by Cooper-Kunz** [comment]
This all makes sense, thank you again for the clarity @calvinchengx!

Could we maybe publish the list of known issues that you're working on for the v0.1.X so that I don't continue to file redundant issues? 😄Or is there's a certain release version I should wait for (v0.2?) that should be feature complete? 

I'd love to start making some tutorial videos, using this in workshops, etc.
